on:
  push:
    branches:
    - source

jobs:
  pages:
    permissions:
        id-token: write
        pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install and build
        run: |
          npm install
          npm run build
      - name: Archive page
        run: |
          tar cvzf github-pages.tar.gz -C build .
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy GitHub Page
        uses: actions/deploy-pages@v1.2.9
   
